version: '3.3'
services:
  db_foodgram:
    image: postgres:13.0-alpine
    volumes:
      - db_foodgram:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: 93652342/foodgram_project:v1.0.1
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/media/ 
    depends_on:
      - db_foodgram
    env_file:
      - ./.env
  frontend:
    image: 93652342/frontend:v.1.0.0
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db_foodgram
  nginx:
    image: nginx:1.19.3
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  db_foodgram: